#!/bin/bash
# Fetch the latest Roblox API Dump from official client tracker

OUTPUT_FILE="${1:-roblox_api_dump.json}"

echo "Fetching latest API version hash..."
VERSION_HASH=$(curl -s "https://setup.rbxcdn.com/versionQTStudio")

if [ -z "$VERSION_HASH" ]; then
    echo "Error: Failed to fetch Roblox Studio version hash."
    exit 1
fi

echo "Active Studio Version: $VERSION_HASH"
echo "Downloading API Dump JSON..."

# This fetches the raw API dump generated by Roblox Studio
curl -s "https://setup.rbxcdn.com/${VERSION_HASH}-API-Dump.json" > "$OUTPUT_FILE"

if [ ! -s "$OUTPUT_FILE" ]; then
    echo "Error: Downloaded file is empty or missing."
    exit 1
fi

FILE_SIZE=$(wc -c < "$OUTPUT_FILE" | xargs)
echo "Success! Saved API Dump to $OUTPUT_FILE ($FILE_SIZE bytes)."
